#!/usr/bin/env bash
set -euo pipefail

EXPERIMENT_NAME="${EXPERIMENT_NAME:-metadata_query_gate_text_random_linear_probe}"
LAYA_MODE="${LAYA_MODE:-mixer}"
CHANNEL_METADATA_MODE="${CHANNEL_METADATA_MODE:-text}"
METADATA_FUSION_MODE="${METADATA_FUSION_MODE:-none}"
CHANNEL_MIXER_RELATION_MODE="${CHANNEL_MIXER_RELATION_MODE:-metadata_query_gate}"
CHANNEL_MIXER_RELATION_SCALE_INIT="${CHANNEL_MIXER_RELATION_SCALE_INIT:-1.0}"

export EXPERIMENT_NAME LAYA_MODE CHANNEL_METADATA_MODE METADATA_FUSION_MODE CHANNEL_MIXER_RELATION_MODE CHANNEL_MIXER_RELATION_SCALE_INIT STATS_METADATA_DIM
exec "$(dirname "$0")/classification_laya_random_linear_probe.sh"
