#!/usr/bin/env bash
set -euo pipefail

EXPERIMENT_NAME="${EXPERIMENT_NAME:-mixer_concat_text_random_linear_probe}"
LAYA_MODE="${LAYA_MODE:-mixer}"
CHANNEL_METADATA_MODE="${CHANNEL_METADATA_MODE:-text}"
METADATA_FUSION_MODE="${METADATA_FUSION_MODE:-concat_kv}"
CHANNEL_MIXER_RELATION_MODE="${CHANNEL_MIXER_RELATION_MODE:-none}"

export EXPERIMENT_NAME LAYA_MODE CHANNEL_METADATA_MODE METADATA_FUSION_MODE CHANNEL_MIXER_RELATION_MODE CHANNEL_MIXER_RELATION_SCALE_INIT STATS_METADATA_DIM
exec "$(dirname "$0")/classification_laya_random_linear_probe.sh"
