#!/usr/bin/env bash
set -euo pipefail

EXPERIMENT_NAME="${EXPERIMENT_NAME:-mixer_text_stats_avg_random_linear_probe}"
LAYA_MODE="${LAYA_MODE:-mixer}"
CHANNEL_METADATA_MODE="${CHANNEL_METADATA_MODE:-text_stats_avg}"
METADATA_FUSION_MODE="${METADATA_FUSION_MODE:-add}"
CHANNEL_MIXER_RELATION_MODE="${CHANNEL_MIXER_RELATION_MODE:-none}"
STATS_METADATA_DIM="${STATS_METADATA_DIM:-384}"

export EXPERIMENT_NAME LAYA_MODE CHANNEL_METADATA_MODE METADATA_FUSION_MODE CHANNEL_MIXER_RELATION_MODE CHANNEL_MIXER_RELATION_SCALE_INIT STATS_METADATA_DIM
exec "$(dirname "$0")/forecasting_laya_random_linear_probe.sh"
